version: "3"

services:
  nexus:
    image: sonatype/nexus3
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"
    networks:
      - xcom-buildstack
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - "jenkins-home:/var/jenkins_home"
    ports:
      - "8082:8080"
    networks:
      - xcom-buildstack
  sonar_db_pgsql:
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - xcom-buildstack
  sonar:
    image: sonarqube
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar_db_pgsql:5432/sonar
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9000:9000"
      - "9002:9002"
    networks:
      - xcom-buildstack
    depends_on:
      - "sonar_db_pgsql"



volumes:
  nexus-data: {}
  jenkins-home: {}
  pg-data: {}

networks:
  xcom-buildstack: {}
